# Generated by Django 6.0.1 on 2026-01-27 23:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(38),
                        ],
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100)),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("ativa", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Rodada",
                "verbose_name_plural": "Rodadas",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("sigla", models.CharField(max_length=3, unique=True)),
                (
                    "escudo",
                    models.ImageField(blank=True, null=True, upload_to="escudos/"),
                ),
            ],
            options={
                "verbose_name": "Time",
                "verbose_name_plural": "Times",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_exibicao", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "ordering": ["nome_exibicao"],
            },
        ),
        migrations.CreateModel(
            name="Classificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posicao", models.PositiveIntegerField()),
                ("pontos_totais", models.PositiveIntegerField(default=0)),
                ("acertos_totais", models.PositiveIntegerField(default=0)),
                ("empates_acertados", models.PositiveIntegerField(default=0)),
                ("vitorias_acertadas", models.PositiveIntegerField(default=0)),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bolao.participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classificação",
                "verbose_name_plural": "Classificações",
                "ordering": ["posicao"],
            },
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                ("gols_casa", models.PositiveIntegerField(blank=True, null=True)),
                ("gols_visitante", models.PositiveIntegerField(blank=True, null=True)),
                ("resultado_finalizado", models.BooleanField(default=False)),
                (
                    "rodada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bolao.rodada"
                    ),
                ),
                (
                    "time_casa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogos_casa",
                        to="bolao.time",
                    ),
                ),
                (
                    "time_visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogos_visitante",
                        to="bolao.time",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jogo",
                "verbose_name_plural": "Jogos",
                "ordering": ["data_hora"],
                "unique_together": {("rodada", "time_casa", "time_visitante")},
            },
        ),
        migrations.CreateModel(
            name="Palpite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resultado_palpite",
                    models.CharField(
                        choices=[
                            ("V", "Vitória do time da casa"),
                            ("E", "Empate"),
                            ("D", "Vitória do visitante"),
                        ],
                        max_length=1,
                    ),
                ),
                ("data_palpite", models.DateTimeField(auto_now_add=True)),
                (
                    "jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bolao.jogo"
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bolao.participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palpite",
                "verbose_name_plural": "Palpites",
                "ordering": ["-data_palpite"],
                "unique_together": {("participante", "jogo")},
            },
        ),
    ]
