# Generated by Django 6.0.1 on 2026-01-28 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="palpite",
            name="resultado_palpite",
        ),
        migrations.AddField(
            model_name="palpite",
            name="gols_casa_palpite",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AddField(
            model_name="palpite",
            name="gols_visitante_palpite",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
    ]
