# Generated by Django 6.0.1 on 2026-01-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0002_remove_palpite_resultado_palpite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participante",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="perfis/"),
        ),
    ]
