# Generated by Django 6.0.1 on 2026-01-28 21:55

import bolao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0003_participante_foto_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=bolao.models.redimensionar_imagem_perfil,
            ),
        ),
    ]
