# Generated by Django 6.0.1 on 2026-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0004_alter_participante_foto_perfil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classificacao",
            name="empates_acertados",
        ),
        migrations.RemoveField(
            model_name="classificacao",
            name="vitorias_acertadas",
        ),
        migrations.AddField(
            model_name="classificacao",
            name="ultimo_saldo",
            field=models.IntegerField(default=0),
        ),
    ]
