# Generated by Django 6.0.1 on 2026-01-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0005_remove_classificacao_empates_acertados_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participante",
            name="invisivel",
            field=models.BooleanField(
                default=False, help_text="Se marcado, não aparecerá na classificação"
            ),
        ),
    ]
