# Generated by Django 6.0.1 on 2026-01-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0006_participante_invisivel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtualizacaoSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("versao", models.CharField(max_length=10, unique=True)),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("data_lancamento", models.DateTimeField(auto_now_add=True)),
                ("ativa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Atualização do Site",
                "verbose_name_plural": "Atualizações do Site",
                "ordering": ["-data_lancamento"],
            },
        ),
        migrations.CreateModel(
            name="AtualizacaoVista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_visualizacao", models.DateTimeField(auto_now_add=True)),
                (
                    "atualizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bolao.atualizacaosite",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bolao.participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atualização Vista",
                "verbose_name_plural": "Atualizações Vistas",
                "unique_together": {("participante", "atualizacao")},
            },
        ),
    ]
