# Generated by Django 6.0.1 on 2026-01-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0007_atualizacaosite_atualizacaovista"),
    ]

    operations = [
        migrations.AddField(
            model_name="atualizacaosite",
            name="link_pagina",
            field=models.URLField(
                blank=True,
                help_text="Link para página específica (opcional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="atualizacaosite",
            name="texto_link",
            field=models.CharField(
                blank=True,
                help_text="Texto do botão do link (ex: 'Ver Jogos ao Vivo')",
                max_length=100,
                null=True,
            ),
        ),
    ]
