# Generated by Django 6.0.1 on 2026-02-08 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0008_atualizacaosite_link_pagina_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(unique=True)),
                ("total_visitas", models.IntegerField(default=0)),
                ("visitantes_unicos", models.IntegerField(default=0)),
                ("usuarios_logados", models.IntegerField(default=0)),
                ("usuarios_anonimos", models.IntegerField(default=0)),
                ("total_pageviews", models.IntegerField(default=0)),
                ("tempo_medio_sessao", models.FloatField(default=0.0)),
                ("bounce_rate", models.FloatField(default=0.0)),
                ("palpites_realizados", models.IntegerField(default=0)),
                ("mobile_visitas", models.IntegerField(default=0)),
                ("desktop_visitas", models.IntegerField(default=0)),
                ("tablet_visitas", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Métrica Diária",
                "verbose_name_plural": "Métricas Diárias",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="PaginaPopular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("titulo", models.CharField(max_length=200)),
                ("visitas_hoje", models.IntegerField(default=0)),
                ("visitas_total", models.IntegerField(default=0)),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Página Popular",
                "verbose_name_plural": "Páginas Populares",
                "ordering": ["-visitas_hoje"],
            },
        ),
        migrations.CreateModel(
            name="SessaoVisita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("data_inicio", models.DateTimeField(auto_now_add=True)),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                ("duracao_minutos", models.FloatField(blank=True, null=True)),
                ("paginas_visitadas", models.IntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
                ("pais", models.CharField(blank=True, max_length=50, null=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dispositivo_tipo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("navegador", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sistema_operacional",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bolao.participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Visita",
                "verbose_name_plural": "Sessões de Visitas",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="AcaoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(
                        choices=[
                            ("page_view", "Visualização de Página"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("palpite", "Palpite Realizado"),
                            ("perfil_edit", "Edição de Perfil"),
                            ("classificacao_view", "Ver Classificação"),
                            ("jogos_ao_vivo", "Ver Jogos ao Vivo"),
                            ("click_button", "Clique em Botão"),
                            ("form_submit", "Envio de Formulário"),
                            ("error_404", "Página Não Encontrada"),
                            ("error_500", "Erro do Servidor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pagina_url", models.URLField(max_length=500)),
                (
                    "pagina_titulo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("tempo_resposta", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadados", models.JSONField(blank=True, null=True)),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acoes",
                        to="bolao.sessaovisita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ação do Usuário",
                "verbose_name_plural": "Ações dos Usuários",
                "ordering": ["-timestamp"],
            },
        ),
    ]
