# Generated by Django 6.0.1 on 2026-02-15 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0009_metricadiaria_paginapopular_sessaovisita_acaousuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, verbose_name="Notificações Ativadas"
                    ),
                ),
                (
                    "nova_rodada",
                    models.BooleanField(
                        default=True, verbose_name="Nova rodada disponível"
                    ),
                ),
                (
                    "lembrete_prazo",
                    models.BooleanField(default=True, verbose_name="Lembrete de prazo"),
                ),
                (
                    "resultados_publicados",
                    models.BooleanField(
                        default=True, verbose_name="Resultados publicados"
                    ),
                ),
                (
                    "ranking_atualizado",
                    models.BooleanField(
                        default=True, verbose_name="Ranking atualizado"
                    ),
                ),
                (
                    "push_subscription",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dados de subscrição push"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "participante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to="bolao.participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Notificações",
                "verbose_name_plural": "Configurações de Notificações",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nova_rodada", "Nova Rodada"),
                            ("lembrete_prazo", "Lembrete de Prazo"),
                            ("resultados", "Resultados Publicados"),
                            ("ranking", "Ranking Atualizado"),
                            ("sistema", "Notificação do Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("mensagem", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviada"),
                            ("delivered", "Entregue"),
                            ("failed", "Falhou"),
                            ("clicked", "Clicada"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "url_acao",
                    models.URLField(
                        blank=True, help_text="URL para onde a notificação direciona"
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("enviada_em", models.DateTimeField(blank=True, null=True)),
                ("clicada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "push_id",
                    models.CharField(
                        blank=True, help_text="ID da notificação push", max_length=100
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Mensagem de erro caso falhe"
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="bolao.participante",
                    ),
                ),
                (
                    "rodada_relacionada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bolao.rodada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-criada_em"],
                "indexes": [
                    models.Index(
                        fields=["participante", "status"],
                        name="bolao_notif_partici_51740c_idx",
                    ),
                    models.Index(
                        fields=["tipo", "criada_em"], name="bolao_notif_tipo_cb8c9b_idx"
                    ),
                ],
            },
        ),
    ]
