# Generated by Django 6.0.2 on 2026-02-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bolao", "0010_notificationsettings_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="vista_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando a notificação foi vista pelo usuário",
                null=True,
            ),
        ),
    ]
